spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1035107821677-ggpbkhoh6dgga15rsvhfncsbaaqvaj9n.apps.googleusercontent.com
            client-secret: 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